table dim_customers
	lineageTag: 841c58a9-10fe-485d-85a9-067627419b8e
	sourceLineageTag: [dbo].[dim_customers]

	measure 'Total Revenue' = SUM(fact_orders[payment_value])
		lineageTag: c00beaf3-cc16-46bb-a187-7403fd32c7fb

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: string
		lineageTag: 606364ce-fd9d-443f-9260-8b15d83461b5
		sourceLineageTag: customer_id
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 5e8b1bd0-ce55-4428-9d43-8cfcc294d0fa
		sourceLineageTag: customer_unique_id
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: aeab3b69-4656-4c1e-9247-ee6c8a0a350c
		sourceLineageTag: customer_city
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 7ee107df-26fb-44ab-acdf-c8f7deaea593
		sourceLineageTag: customer_state
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition dim_customers = entity
		mode: directLake
		source
			entityName: dim_customers
			schemaName: dbo
			expressionSource: 'DirectLake - ecommerce_lakehouse'

